# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifieddomain',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='VerifiedDomain',
        ),
    ]
